apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-pod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/app-creds"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: secret-creds
