apiVersion: v1
<<<<<<< HEAD
kind: Pod
metadata:
  name: redis
  namespace: web
spec: 
  containers: 
  - image: redis
    name: redis
    ports:
    - containerPort: 9090
      name: redis
      protocol: TCP
=======
kind: Namespace
metadata:
  name: web
  labels:
    name: web
>>>>>>> b238a2a37433304e896f07c353eb95d30c3ca719
