apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app_runtime_stage: staging
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app_runtime_stage: staging
    spec:
      containers:
      - image: nginx
        name: maxapp
